export interface Project {
  name: string;
  title: string;
  description: string;
  language: string | null;
  topics: string[];
  url: string;
  updated: string;
  /** Live, clickable demo of the project, when there is one. */
  demo?: string;
  /** A single headline result worth surfacing on the card. */
  metric?: string;
  /** Preview image in public/projects, when the project has something to show. */
  image?: string;
  /** Alt text describing what the preview actually shows. */
  imageAlt?: string;
}

/**
 * Preview images, keyed by repo name. Screenshots of the live demos plus
 * result figures from the repos themselves; see public/projects.
 */
const previews: Record<string, string> = {
  'cnn-explorer': 'A digit drawn on the pad, with every layer of the 3D network lit up and the prediction at 100%',
  'flappy-bird-rl': 'The trained agent mid-flight between pipes, beside its live action probabilities',
  'bpe-tokenizer': 'A sentence split into coloured token chips above the merge-by-merge walkthrough',
  'slime-mold-simulation': 'The organic network of paths the simulated slime mold leaves behind',
  'matrix-green-letters': 'Columns of green glyphs falling down a black screen',
  'text-to-image': 'A grid of sketches generated by the diffusion model across ten categories',
  'fire-detection': 'A drone photo of a snowy forest, the predicted fire mask, and the two overlaid',
  'lettersnumbers-classifier': 'A webcam frame of a chess scoresheet with the predicted characters marked',
  'coins-detection': 'Euro coins on a flat surface, each detected and labelled by value',
  'emergency-vehicle-detection':
    'The live demo showing a siren detected at p = 0.9996, above the chroma bands it was classified from',
  radai: 'The news digest listing AI stories by significance, each with a button to draft a LinkedIn post',
  'rag-system': 'A natural-language query returning ranked clothing items with their rerank scores',
  'mlops-cicd-pipeline': 'A grid of MNIST digits with the model prediction above each one',
};

/** Repo name to image slug, where they differ. */
const imageSlugs: Record<string, string> = {
  'BPE-tokenizer': 'bpe-tokenizer',
};

/** Human-readable titles and descriptions for repos where GitHub metadata is thin. */
const overrides: Record<
  string,
  { title?: string; description?: string; topics?: string[]; demo?: string; metric?: string }
> = {
  'cnn-explorer': {
    title: 'CNN Explorer',
    description:
      'An interactive 3D visualization of a convolutional network trained on MNIST. Draw a digit, watch every layer react, click any neuron to see the arithmetic behind it, and retrain the network in the browser.',
    metric: '98.86% MNIST test accuracy',
  },
  'flappy-bird-rl': {
    title: 'Flappy Bird RL',
    description:
      'A Gymnasium environment and PPO agent, with a controlled ablation testing whether lookahead features caused an apparent gain. They did not: the improvement came from a longer step budget.',
    metric: '171.7 pipes over 30 held-out seeds',
  },
  radai: {
    title: 'RadAI',
    description:
      'A React and Firebase app that surfaces recent AI news on demand and drafts LinkedIn posts about it, using Claude with web search and structured outputs behind server-side access control.',
    topics: ['react', 'typescript', 'firebase', 'claude', 'llm', 'cloud-functions'],
  },
  'emergency-vehicle-detection': {
    title: 'Emergency Vehicle Detection',
  },
  'BPE-tokenizer': {
    title: 'BPE Tokenizer',
  },
  'text-to-image': {
    title: 'Text-to-Image Diffusion',
    description:
      'A UNet-based DDPM/DDIM diffusion model built from scratch, with EMA and classifier-free guidance, trained on Quick Draw sketches.',
    topics: ['diffusion', 'ddpm', 'ddim', 'generative-ai', 'pytorch', 'unet'],
  },
  'rag-system': {
    title: 'Fashion RAG Search',
    topics: ['rag', 'semantic-search', 'lancedb', 'reranking', 'streamlit'],
  },
  'coins-detection': {
    title: 'Coin Detection',
  },
  'lettersnumbers-classifier': {
    title: 'Chess Notation Classifier',
  },
  'fire-detection': {
    title: 'Forest Fire Segmentation',
  },
  'slime-mold-simulation': {
    title: 'Slime Mold Simulation',
  },
  'matrix-green-letters': {
    title: 'Matrix Rain',
    description:
      'A small creative-coding piece rendering the falling green glyph effect in the browser with plain JavaScript and canvas.',
    topics: ['creative-coding', 'canvas', 'javascript'],
  },
  'mlops-cicd-pipeline': {
    title: 'MLOps CI/CD Pipeline',
    topics: ['ci-cd', 'github-actions', 'docker', 'pytorch', 'pytest'],
  },
};

/**
 * Repos excluded from the portfolio grid: the profile README repo, forks,
 * and this site itself (it is the thing the visitor is already looking at).
 */
const excluded = new Set(['moralesangel', 'MQCOM-software', 'portfolio']);

/** Order the most representative work first; anything unlisted follows, newest first. */
const featuredOrder = [
  'cnn-explorer',
  'flappy-bird-rl',
  'text-to-image',
  'emergency-vehicle-detection',
  'radai',
  'BPE-tokenizer',
  'rag-system',
  'fire-detection',
  'lettersnumbers-classifier',
  'coins-detection',
  'slime-mold-simulation',
];

function titleize(name: string): string {
  return name
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

interface GitHubRepo {
  name: string;
  description: string | null;
  language: string | null;
  topics?: string[];
  html_url: string;
  /** Repo "website" field; used as the live demo link when present. */
  homepage?: string | null;
  updated_at: string;
  fork: boolean;
}

function normalize(repo: GitHubRepo): Project {
  const o = overrides[repo.name] ?? {};
  return {
    name: repo.name,
    title: o.title ?? titleize(repo.name),
    description: o.description ?? repo.description ?? '',
    language: repo.language,
    topics: (repo.topics?.length ? repo.topics : o.topics) ?? [],
    url: repo.html_url,
    updated: repo.updated_at,
    // Demo links come from the repo's "Website" field, so adding a demo to a
    // project needs no change here. An override is only an escape hatch for a
    // homepage that is not a demo (docs, a paper, a product page).
    // GitHub returns "" (not null) for repos with no website, so test
    // truthiness rather than nullishness.
    demo: o.demo || repo.homepage || undefined,
    metric: o.metric,
    ...previewFor(repo.name),
  };
}

/** Preview image paths for a repo, or nothing when it has no image. */
function previewFor(name: string): { image?: string; imageAlt?: string } {
  const slug = imageSlugs[name] ?? name;
  const alt = previews[slug];
  if (!alt) return {};
  return { image: slug, imageAlt: alt };
}

/** Used when the GitHub API is unreachable at build time. */
const fallback: GitHubRepo[] = [
  {
    name: 'cnn-explorer',
    description:
      'See how a convolutional neural network reads handwriting: an interactive 3D visualization of a CNN trained on MNIST, with in-browser training.',
    language: 'JavaScript',
    topics: ['cnn', 'deep-learning', 'tensorflowjs', 'threejs', 'visualization', 'mnist'],
    html_url: 'https://github.com/moralesangel/cnn-explorer',
    homepage: 'https://moralesangel.github.io/cnn-explorer/',
    updated_at: '2026-09-27T00:00:00Z',
    fork: false,
  },
  {
    name: 'flappy-bird-rl',
    description:
      'Flappy Bird as a Gymnasium environment with a PPO agent (171.7 pipes, held-out mean). Includes a controlled ablation showing how observation-space design drove a ~10x performance difference.',
    language: 'Python',
    topics: ['reinforcement-learning', 'ppo', 'gymnasium', 'stable-baselines3', 'python'],
    html_url: 'https://github.com/moralesangel/flappy-bird-rl',
    homepage: 'https://moralesangel.github.io/flappy-bird-rl/',
    updated_at: '2026-09-26T00:00:00Z',
    fork: false,
  },
  {
    name: 'radai',
    description: "React + Firebase + Claude app that surfaces yesterday's AI news and drafts LinkedIn posts about it",
    language: 'TypeScript',
    topics: [],
    html_url: 'https://github.com/moralesangel/radai',
    updated_at: '2026-09-23T00:00:00Z',
    fork: false,
  },
  {
    name: 'text-to-image',
    description: null,
    language: 'Jupyter Notebook',
    topics: [],
    html_url: 'https://github.com/moralesangel/text-to-image',
    updated_at: '2026-08-18T19:03:30Z',
    fork: false,
  },
  {
    name: 'emergency-vehicle-detection',
    description:
      'A compact pipeline for detecting emergency vehicles from audio using deep learning. Includes data download and preprocessing, MFCC/LFCC/Chroma feature extraction, model training (autoencoders for dimensionality reduction and FFNN/CNN/LSTM classifiers) and performance evaluation.',
    language: 'Jupyter Notebook',
    topics: ['deep-learning', 'audio-classification', 'autoencoders', 'siren-detection', 'smart-city', 'feature-extraction'],
    html_url: 'https://github.com/moralesangel/emergency-vehicle-detection',
    updated_at: '2025-11-23T22:43:18Z',
    fork: false,
  },
  {
    name: 'BPE-tokenizer',
    description:
      'A clean, educational implementation of the Byte Pair Encoding algorithm used in modern language models like GPT.',
    language: 'Jupyter Notebook',
    topics: ['bpe', 'tokenization', 'llm', 'nlp', 'transformers', 'generative-ai'],
    html_url: 'https://github.com/moralesangel/BPE-tokenizer',
    updated_at: '2025-11-23T22:07:31Z',
    fork: false,
  },
  {
    name: 'rag-system',
    description: null,
    language: 'Python',
    topics: [],
    html_url: 'https://github.com/moralesangel/rag-system',
    updated_at: '2026-06-07T17:52:52Z',
    fork: false,
  },
  {
    name: 'fire-detection',
    description:
      'This project will try to segment forest images taken by a drone, classifying each pixel by either forest or fire (segmentation technique)',
    language: 'MATLAB',
    topics: ['cnn', 'deep-learning', 'drone', 'fire-detection', 'segmentation'],
    html_url: 'https://github.com/moralesangel/fire-detection',
    updated_at: '2024-06-03T01:16:34Z',
    fork: false,
  },
  {
    name: 'lettersnumbers-classifier',
    description: 'Letters and numbers classifier for chess games using computer vision and neural networks.',
    language: 'MATLAB',
    topics: ['chess', 'computer-vision', 'neural-networks', 'real-time', 'webcam', 'feature-extraction'],
    html_url: 'https://github.com/moralesangel/lettersnumbers-classifier',
    updated_at: '2024-06-04T10:41:54Z',
    fork: false,
  },
  {
    name: 'coins-detection',
    description: 'This project will try to detect every type of coin within an image using Computer Vision techniques.',
    language: 'MATLAB',
    topics: ['computer-vision', 'classification', 'matlab', 'regionprops'],
    html_url: 'https://github.com/moralesangel/coins-detection',
    updated_at: '2025-11-23T21:37:41Z',
    fork: false,
  },
  {
    name: 'slime-mold-simulation',
    description:
      'A simulation of slime mold behavior using p5.js, inspired by the movement and pattern formation of real slime molds. Particles leave visual traces as they explore, forming organic paths.',
    language: 'JavaScript',
    topics: ['biology', 'creative-coding', 'simulation', 'javascript'],
    html_url: 'https://github.com/moralesangel/slime-mold-simulation',
    updated_at: '2024-09-30T00:31:35Z',
    fork: false,
  },
  {
    name: 'matrix-green-letters',
    description: null,
    language: 'JavaScript',
    topics: [],
    html_url: 'https://github.com/moralesangel/matrix-green-letters',
    updated_at: '2026-08-27T16:14:38Z',
    fork: false,
  },
];

export async function getProjects(): Promise<Project[]> {
  let repos: GitHubRepo[] = fallback;

  try {
    const headers: Record<string, string> = {
      Accept: 'application/vnd.github+json',
      'User-Agent': 'moralesangel-portfolio',
    };

    // In CI, authenticate to avoid the low unauthenticated rate limit.
    // Astro exposes build-time env vars here, so no @types/node is needed.
    const token = import.meta.env.GITHUB_TOKEN;
    if (token) headers.Authorization = `Bearer ${token}`;

    const res = await fetch('https://api.github.com/users/moralesangel/repos?per_page=100&sort=updated', {
      headers,
    });
    if (res.ok) {
      const live = (await res.json()) as GitHubRepo[];
      if (Array.isArray(live) && live.length) repos = live;
    }
  } catch {
    // Offline build: keep the curated fallback.
  }

  const projects = repos.filter((r) => !r.fork && !excluded.has(r.name)).map(normalize);

  return projects.sort((a, b) => {
    const ia = featuredOrder.indexOf(a.name);
    const ib = featuredOrder.indexOf(b.name);
    if (ia !== -1 && ib !== -1) return ia - ib;
    if (ia !== -1) return -1;
    if (ib !== -1) return 1;
    return b.updated.localeCompare(a.updated);
  });
}
